# This is a sample Docker compose file to run the application locally
version: '3'
services:
  pubsub-emulator:
    image: google/cloud-sdk:emulators
    ports:
      - "8085:8085"
    environment:
      - PUBSUB_PROJECT_ID=sentimental-analysis
    command: gcloud beta emulators pubsub start --project=sentimental-analysis --host-port=0.0.0.0:8085
  
  datastore-emulator:
    image: google/cloud-sdk:emulators
    ports:
      - "8432:8432"
    environment:
      - DATASTORE_PROJECT_ID=sentimental-analysis 
    command: gcloud beta emulators datastore start--project=sentimental-analysis --host-port=0.0.0.0:8432

  producer-app:
    build:
      context: ./producer
      dockerfile: Dockerfile
    ports:
      - "8086:8080"
    environment:
      - OUTPUT_TOPIC_ID=sentimental-analysis
      - PROJECT_ID=sentimental-analysis
      - PUBSUB_EMULATOR_HOST=pubsub-emulator:8085

  consumer-app:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    ports:
      - "8087:8080"
    environment:
      - PROJECT_ID=sentimental-analysis
      - DATASTORE_EMULATOR_HOST=datastore-emulator:8432
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/credentials.json
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/tmp/keys/credentials.json
