name: Build and zip consumer function

on:
  push:
    branches:
      - main
    paths:
      - 'functions/consumer/**'

jobs:
  build-functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0' 

      - name: Build consumer
        run: dotnet build ./functions/consumer

      - name: Publish consumer
        run: dotnet publish ./functions/consumer/consumer-function.csproj --configuration Release --output ./publish/consumer

      - name: Zip consumer
        run: zip -r consumer.zip ./publish/consumer

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.FUNCTION_STORAGE_SERVICE_ACCOUNT_JSON }}
  
      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'producer.zip'
          destination: 'gs://${{ secrets.FUNCTION_STORAGE_BUCKET }}/producer.zip'