name: Docker compose dev

on:  
  workflow_dispatch:
  pull_request:
    paths:
      - 'functions/**'
  push:
    paths:
      - 'functions/**'

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: docker-compose.yml
          up-flags: --build

      - name: Loop curl until services are up
        run: |
          timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8085/v1/projects/sentimental-analysis/topics)" != "200" ]]; do sleep 5; done' || false    
          timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8432)" != "200" ]]; do sleep 5; done' || false    

      - name: Setup PubSub
        run: |
          curl -X PUT "http://localhost:8085/v1/projects/sentimental-analysis/topics/sentimental-analysis"
          curl -X PUT "http://localhost:8085/v1/projects/sentimental-analysis/subscriptions/sentimental-analysis-subscription" -H "Content-Type: application/json" --data '{"topic":"projects/sentimental-analysis/topics/sentimental-analysis","pushConfig":{"pushEndpoint":"http://consumer-app:8080"}}'

      - name: Test E2E
        run: |
          curl -X POST -d 'hello world' localhost:8086
          curl -X POST -d 'hello good world' localhost:8086
          curl -X POST -d 'hello bad world' localhost:8086

      - name: Wait for results
        run: sleep 10

      - name: Check datastore for results
        run: |
          docker compose logs -n 100 | grep -q "Inserted key" || exit 1

