name: Build and zip producer function

on:
  push:
    branches:
      - main
    paths:
      - 'functions/producer/**'

jobs:
  build-functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'

      - name: Build producer
        run: dotnet build ./functions/producer

      - name: Publish producer
        run: dotnet publish ./functions/producer/producer-function.csproj --configuration Release --output ./publish/producer

      - name: Zip producer
        run: zip -r producer.zip ./publish/producer

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.FUNCTION_STORAGE_SA_KEY }}
  
      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'producer.zip'
          destination: 'gs://${{ env.FUNCTION_STORAGE_BUCKET }}/producer.zip'