name: Terraform Plan and Manual Apply

on:
  push:
    paths:
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.4

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform

      - name: Create Manual Apply Trigger
        id: manual-apply
        run: echo "::set-output name=apply::true"
        if: success()

      - name: Wait for Manual Apply
        id: wait-for-apply
        run: |
          if [ "${{ steps.manual-apply.outputs.apply }}" = "true" ]; then
            echo "Waiting for manual apply..."
            sleep 30  # Adjust the time interval if needed
          else
            echo "Manual apply not required."
          fi
        timeout-minutes: 120  # Adjust the timeout duration if needed

      - name: Apply Terraform Changes
        if: ${{ steps.wait-for-apply.outcome == 'success' }}
        run: terraform apply tfplan
        working-directory: ./terraform
